In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [3]:
#read train and test files
train_file = pd.read_csv('mnist_train.txt')
test_f = pd.read_csv('mnist_test.txt')
test_file = test_f.iloc[:,0:784]

In [4]:
df_x=train_file.iloc[:,1:]
df_y=train_file.iloc[:,0]

In [5]:
train_file.head()

5  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...    0.608  0.609  0.610  \
0  0  0    0    0    0    0    0    0    0    0  ...        0      0      0   
1  4  0    0    0    0    0    0    0    0    0  ...        0      0      0   
2  1  0    0    0    0    0    0    0    0    0  ...        0      0      0   
3  9  0    0    0    0    0    0    0    0    0  ...        0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...        0      0      0   

   0.611  0.612  0.613  0.614  0.615  0.616  0.617  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [6]:
test_file.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...    0.657  0.658  0.659  \
0  2  0    0    0    0    0    0    0    0    0  ...        0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...        0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...        0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...        0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...        0      0      0   

   0.660  0.661  0.662  0.663  0.664  0.665  0.666  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 784 columns]

In [7]:
num_train,num_validation = int(len(train_file)*0.8),int(len(train_file)*0.2)
num_train,num_validation
x_train,y_train=train_file.iloc[:num_train,1:].values,train_file.iloc[:num_train,0].values
x_validation,y_validation=train_file.iloc[num_train:,1:].values,train_file.iloc[num_train:,0].values
print(x_train.shape)
print(y_train.shape)
print(x_validation.shape)
print(y_validation.shape)

(47999, 784)
(47999,)
(12000, 784)
(12000,)


In [12]:
clf=RandomForestClassifier(n_estimators=100,max_features="auto", max_depth=None)
RF = clf.fit(x_train,y_train)
RF

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [13]:
prediction_validation = clf.predict(x_validation)
accuracy = accuracy_score(y_validation,prediction_validation)
error = 1 - accuracy
print("Validation Accuracy   : " ,accuracy)
print("Validation Error      : ", round(error, 4))
print("Error Percentage      : ",(round(error, 4) *100), "%")

Validation Accuracy   :  0.96925
Validation Error      :  0.0308
Error Percentage      :  3.08 %


In [14]:
from sklearn.metrics import classification_report
print ("Classification Report")
print(classification_report(y_validation, prediction_validation))
print ("Confusion Matrix Report")
cm = confusion_matrix(y_validation, prediction_validation)
print(cm)

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1194
           1       0.98      0.99      0.99      1272
           2       0.96      0.96      0.96      1196
           3       0.97      0.96      0.96      1242
           4       0.98      0.97      0.97      1187
           5       0.97      0.95      0.96      1097
           6       0.97      0.99      0.98      1170
           7       0.98      0.97      0.98      1297
           8       0.95      0.96      0.96      1198
           9       0.95      0.95      0.95      1147

   micro avg       0.97      0.97      0.97     12000
   macro avg       0.97      0.97      0.97     12000
weighted avg       0.97      0.97      0.97     12000

Confusion Matrix Report
[[1178    0    4    0    0    0    3    0    7    2]
 [   0 1258    5    2    2    1    0    1    3    0]
 [   7    2 1146    4    5    1    6   10   12    3]
 [   4    0    8 1192    0   13    2

In [15]:
from sklearn.model_selection import cross_val_score
rf=RandomForestClassifier(n_estimators=100)
rf.fit(df_x, df_y)
score = cross_val_score(rf, df_x, df_y)
print(score)
print ("The mean accuracy :",np.mean(score))

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


[0.96530694 0.96219811 0.96564313]
The mean accuracy : 0.9643827257144993
